jobs:
  - name: J1
    type: runSh
    steps:
      - TASK:
        - script: echo versionName=j1 > $JOB_STATE/my_state.env
        - script: echo foo=j1 >> $JOB_STATE/my_state.env
      - OUT: my_state
        overwrite: false

  - name: J2
    type: runSh
    steps:
      - TASK:
        - script: echo versionName=j2 > $JOB_STATE/my_state.env
        - script: echo bar=j2 >> $JOB_STATE/my_state.env
      - OUT: my_state
