jobs:
  - name: J1
    type: runSh
    steps:
      - TASK:
        - script: cat /build/OUT/my_state/version.json
        - script: echo versionName=j1 > $JOB_STATE/my_state.env
        - script: echo foo=j1 >> $JOB_STATE/my_state.env
      - OUT: my_state
        overwrite: true

  - name: J2
    type: runSh
    steps:
      - TASK:
        - script: cat /build/OUT/my_state/version.json
        - script: echo versionName=j2 > $JOB_STATE/my_state.env
        - script: echo bar=j2 >> $JOB_STATE/my_state.env
      - OUT: my_state
        overwrite: true
        
  - name: J3
    type: runSh
    steps:
      - TASK:
        - script echo foo=j3 > $JOB_STATE/my_params.env
        - script echo versionName=j3-$(date) > $JOB_STATE/my_params.env
      - OUT: my_params
  
  - name: J4
    type: runSh
    steps:
      - IN: my_params
      - TASK:
        - cat /build/IN/my_params/params/version.json
